version: 2.1
orbs:
  node: circleci/node@4
  codecov: codecov/codecov@1
jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - codecov/upload

workflows:
  version: 2
  test:
    jobs:
      - test
